---
- name: "deploy dockerized nagios with ansible"
  gather_facts: true
  hosts: vg-compute-09
  become: yes
  roles:
    - common
    # - jenkins-slave  
    - docker
    # - docker-init
    # - elasticsearch
    # - kibana
    # - logstash
    # - heartbeat
    # - nginx
    # - image-scanner

- name: "deploy nagios w ansible role"
  gather_facts: true
  hosts: vg-compute-10
  become: yes
  roles:
    - common
    # - jenkins  
    # - jenkins-casc
 
# - name: "deploy ELK with filebeat"
#   gather_facts: true
#   hosts: vg-compute-11
#   become: yes
#   roles:
#     - common
#     - jenkins-slave  
#     - docker
#     - docker-init
#     - clean
#     - elasticsearch
#     - kibana
#     - logstash
#     - filebeat
#     - nginx  
#     - image-scanner  


- name: "deploy dockerized nagios with ansible"
  gather_facts: true
  hosts: vg-compute-12
  become: yes
  roles:
    - common
    # - jenkins-slave  
    - docker
    # - docker-init
    # - elasticsearch
    # - kibana
    # - logstash
    # - heartbeat
    # - nginx
    # - image-scanner  

- name: "deploy dockerized nagios with ansible"
  gather_facts: true
  hosts: vg-compute-13
  become: yes
  roles:
    - common
    # - jenkins-slave  
    - docker
    # - docker-init
    # - elasticsearch
    # - kibana
    # - logstash
    # - heartbeat
    # - nginx
    # - image-scanner