---
- name: "deploy dockerized nagios with ansible"
  gather_facts: true
  hosts: vg-compute-09
  become: yes
  roles:
    - common
    - docker


- name: "deploy nagios w ansible role"
  gather_facts: true
  hosts: vg-compute-10
  become: yes
  roles:
    - common


- name: "deploy dockerized nagios with ansible"
  gather_facts: true
  hosts: vg-compute-12
  become: yes
  roles:
    - common
    - docker
    # - docker-init


- name: "deploy dockerized nagios with ansible"
  gather_facts: true
  hosts: vg-compute-13
  become: yes
  roles:
    - common 
    - docker
